# Generated by Django 4.0.2 on 2022-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='p', max_length=200),
            preserve_default=False,
        ),
    ]
